### ISSUE TITLE
Why does my utterance's score keep decreasing?

### ISSUE THREAD

**Issue by saeho** [axa-group/nlp.js#115]
Hello,

I have built an app where users constantly train new intents/utterances & answers into the model. And then the model constantly re-trains itself every 4 minutes.

I have noticed that the scores of utterances that users ask keep decreasing.

For example, one user created an utterance/intent for "What is your favorite color?". Typing the exact utterance used to return ~.9 score. Now it returns ~.3 score.

What is the cause of this and how can I reliably solve this problem?

**Comment by saeho** [comment]
To add to this issue/question ... I'm not sure if my score is decreasing, but it certainly looks like my intents with "conditions" have a significantly lower score value... even though the utterance matches letter by letter...

Any guidance on how and why the score is so low would be deeply appreciated.

**Comment by jesus-seijas-sp** [comment]
Hello,

I tested to retrain 100 times one model with 52 intents. Conclussions about that retraining:
- Having only Logistic Regression Classifier, scores are always the same
- Having also neural, scores are slightly different, but not decreasing, simply moving near the same values

About your problem, without the corpus to check, it's impossible to see what's happening. But I can guess that:
- You are having so many utterances
- Utterances that should be in the same intent are in different intents.
- You train intents with only one utterance.

That's why usully nobody let's a chatbot to be trained by the users. The trainers are choosen by those that knows the business of the chatbot. Because something like this can happen:

user1> train "What is your favourite color" as "color"
user2> Train "What is your favourite color" as "favourite_color"
user3> Train "What is your color favourite" as "whatever"
...

So perhaps you can share your corpus to check.

**Comment by saeho** [comment]
You are right, I was actually about to reply that my post was wrong, the math was off and it was something wrong I did.

I would really hate to challenge the integrity of this great package. I'm terribly sorry for my mistake.

I still do have utterance related accuracy issues but it's not as severe as I originally reported.

Also, @j2l i did not make any code modifications.

I'm going to look at the numbers again and re-post my issue in a little bit.

**Comment by saeho** [comment]
Ok, to conclude this issue, it seems short messages results in very small score values (~.2 average). But since it's universally affected to all intents and consistent, it's not a major problem. It was only a problem when I expected all messages to result in similar .7 ~ .9 scores.

Thank you very much for your work in this package.
