### ISSUE TITLE
Add Korean Language

### ISSUE THREAD

**Issue by jechazelle** [axa-group/nlp.js#136]
Hi !
I would like to know if the korean language will soon be supported ?
Thank you !

**Comment by jesus-seijas-sp** [comment]
Hello! I added support for any language in version https://github.com/axa-group/nlp.js/releases/tag/2.4.0

I added examples using Korean and even Klingon: https://github.com/axa-group/nlp.js/blob/master/docs/example-with-languages.md

In the case of korean, the support is through tokenizer but no stemmer. But I also updated the benchmark in order to understand that at least for english, with stemmer the score is 0.93 and with only tokenizer the score is 0.91: https://github.com/axa-group/nlp.js/blob/master/docs/benchmarking.md

**Comment by jesus-seijas-sp** [comment]
Hello @jechazelle can you confirm if is solved and if it works in korean? 
Thank you!

**Comment by jesus-seijas-sp** [comment]
Solved in 2.4.0
