### ISSUE TITLE
Single classifier export/import

### ISSUE THREAD

**Issue by DiegoRBaquero** [axa-group/nlp.js#147]
Coming from https://github.com/axa-group/nlp.js/issues/137, but that was about the breaking change, this is about feature request.

**Is your feature request related to a problem? Please describe.**
The import/export is only featured inside the NLP manager, but not for one classifier.

**Describe the solution you'd like**
Include the import/export functionality for a classifier

**Describe alternatives you've considered**
I currently do the process on my own, but would be nice to have.

**Additional context**

Currently, what I have to do this for one classifier only is: 

```js
      const classifier = new NlpClassifier({ language: 'es' })

      ...

      await classifier.train()

      const newModel = {}
      newModel.language = classifier.settings.language
      newModel.docs = classifier.docs
      newModel.features = classifier.features
      newModel.logistic = {}
      ...

      // save newModel to DB
```

**Comment by jesus-seijas-sp** [comment]
Hello @DiegoRBaquero 
Since version 3.0.0 all classifiers has a toObj and fromObj methods to do the export/import into objects that can be serialized to JSON. This is also included in all NLU classes.
Also, Classifier class has an static method fromObj that works as a Factory, so it build an instance of the correct class. The BaseNLU class has also an static method fromObj that works as Factory for NLU classes.

**Comment by jesus-seijas-sp** [comment]
Solved in 3.x
