### ISSUE TITLE
Train not async

### ISSUE THREAD

**Issue by DiegoRBaquero** [axa-group/nlp.js#148]
This commit https://github.com/axa-group/nlp.js/commit/4af738314d11c64aaaf02d95d055a47c335ca219#diff-17f0d3c08759c7e20efe478795fc436bR92 reverts the train async. Blocking the event-loop, breaking servers and async apps.

Why was this done?

**Comment by jesus-seijas-sp** [comment]
Async training was blocking the event loop in some SO, and it blocked the test execution also in travis... Right now the neural network class is no longer based in external dependendies, so the train method can be written to be async again.

**Comment by vvscode** [comment]
@jesus-seijas-sp I missed the moment when you reverted those changes (docs not updated)

Can you describe what was wrong?
are you going restore threads support?

**Comment by jesus-seijas-sp** [comment]
Well, it's because the evolution of the library.

At the beginning the situation was that only the Logistic Regression Classifer existed, and the library only workend in backend. With LRC and backend, to achive a better performance while training, to do multi-thread seemed a good idea, but at the end is a question of dividing the time over the number of cores, so if the time is 60 secs and 2 cores, then 30 secs seems good... the problem with that is that the O of the algorithm is exponential given the number of observations, so when the time is 1 week... to have it trained in 3.5 days is not an option.

Also, LRC has not the best score, using SIGDIAL22 to score the NLU, with LRC the best result was lower than 0.9.

Then we passed to another situation, with brain.js:
- Logistic Regression Classifier: the situation is the one above
- Bayes Classifier: don't need training, but the score is too bad because is pure statistical.
- Multilabel Classifier: The score was 0.94, the best in the market. But the time to train still not good. Also the async training crashed in some windows SO, like windows 7. The root cause is the use of a libraryfor the async, that seems that sometimes freezes the process during minutes, so it cause to have too long trainings, and also to crash the tests because timeout.
- Binary Relevance Classifier: based also in brain.js, so same situation.

During this phase, the multithreaded was removed because 3 reasons:
- 1. Does not attack the root cause, that is the performance of the algorithm
- 2. Not usable in browser.
- 3. Most deployments are mono-core, so it doesn't help

And currently the situation is:
- LRC
- Bayes
- Multilabel Classifier: removed brain.js in favor of own code, in the console-log example the training time got reduced from 108 seconds to 3 seconds, that is a significative improvement
- Binary Relevance Classifier: same situation as Multilabel Classifier.

Also, now the training is by domain, so when you have several domains each domain is trained separately, that is also a win both in score and performance, and there is an upper neural network that given an utterance is able to determine the domain, and then the NN of the domain determine the intent.

Right now I don't think that multithread will be of help, but yes async to don't block the event loop. Even without async, the event loop can not be locked using a child-process, as shown here: https://github.com/axa-group/nlp.js-app/blob/master/server/trainers/nlpjs-trainer.js
