### ISSUE TITLE
Something wrong in Score's logic

### ISSUE THREAD

**Issue by SherifBashar** [axa-group/nlp.js#158]
Hi ,

I'm a little bit confused after trying this example 
https://github.com/axa-group/nlp.js/tree/master/examples/console-bot

After training I wrote >>> " how "

I got this result : Wonderful! Thanks for asking - greetings.howareyou - 0.9550303053972293

Don't you think the score is too huge for only the " how " word ?

Please advise .. thanks in advance.

![Screen Shot 2019-03-19 at 2 03 15 AM](https://user-images.githubusercontent.com/32583441/54571441-601a7680-49eb-11e9-8220-03ea941b1754.png)

**Comment by jesus-seijas-sp** [comment]
This is normal, given the training data.
"how are you" contains 3 words: "how", "are" and "you". "are" appears 86 times in the training data in different intents, and "you" appears 254 times.
"how" appears only 9 times:
"how old is your platform", "how old are you" => agent.age
"how boring you are" => agent.boring
"how smart you are" => agent.clever
"how is your day", "how is your day going", "how are you", "how are you doing" => greetings.howareyou
"how excited I am" => user.excited

That means that "you" and "are" will get a low weight for the intents, while "how" will get a big weight into the agent.age, agent.boring, agent.clever, greetings.howareyou and user.excited intents. But if you analyze the utterances, removing the "are" and the "you" (because will have a small weight) you get into this kind of utterances:
"how old is platform", "how old" => agent.age
"how boring" => agent.boring
"how smart" => agent.clever
"how is day", "how is day going", "how", "how doing" => greetings.howareyou
"how excited I am" => user.excited

As you can see, there are more utterances with the feature how into the intent greetings.howareyou, and there is even one that is the pure "how" word without any other. So that means that for this intent, the feature "how" will have the biggest weight and the score will be bigger than into any other intent.

That's why in chatbots, the NLP is always being retrained with the history of sentences that you have from the users. In this case, if you want to map "how" into a "None" intent, then add it:
  manager.addDocument('en', 'how', 'None');

And then you will get something like this:
"how" => intent None with score 0.54, while next intent is greetings.howareyou with score 0.12
"how are you" => intent greetings.howareyou with score 0.96

**Comment by SherifBashar** [comment]
Dear,

Thanks for your prompt response , I got your point and manager.addDocument('en', 'how', 'None'); is a good solution for the situation.

Many thanks again for your reply.

**Comment by jesus-seijas-sp** [comment]
Solved
