### ISSUE TITLE
Adding recognizerID's without using the Microsoft Bot Framework

### ISSUE THREAD

**Issue by Aliyss** [axa-group/nlp.js#230]
**Is your feature request related to a problem? Please describe.**
Maybe I haven't found it, but I wanted to request sessions. As far as I've seen this only works with the Microsoft Bot Framework.

**Describe the solution you'd like**
A possibility to recognize the user and enable slot-filling without the Microsoft Bot Framework. Possibly passing through a recognizerID and then having the Memory based on those values.

**Comment by ericzon** [comment]
Maybe I'm wrong but I think this is out of the scope of this library. Something similar could be achieved using nlp.js + context or storing in db the entities extracted of the conversation, related with an user id.

**Comment by Aliyss** [comment]
@ericzon

Not so sure about it being outside of the library. Could be. I just noticed that the possibility exists in dialogflow to pass on an id as context. Thus I was wondering if it were possible to adjust/extract the recognizer to work without the bot framework. Otherwise I would have to keep storing stuff and reloading the nlp model per user.

**Comment by jesus-seijas-sp** [comment]
Hello, if you take a look into the ConversationContext class  you will notice that is an abstract class to work with a context.
https://github.com/axa-group/nlp.js/blob/master/lib/recognizer/conversation-context.js

there you will notice that only a method is implemented: the one that given a session object identifies the conversation id:

```javascript
getConversationId(session) {
    if (
      session &&
      session.message &&
      session.message.address &&
      session.message.address.conversation
    ) {
      return session.message.address.conversation.id;
    }
    // eslint-disable-next-line no-underscore-dangle
    if (session && session._activity && session._activity.conversation) {
      // eslint-disable-next-line no-underscore-dangle
      return session._activity.conversation.id;
    }
    return undefined;
  }
```

This class is for inherit so the storage or other options are implemented by the child classes. One example is the MemoryConversationContext, that is an implementation of the context in memory without database:
https://github.com/axa-group/nlp.js/blob/master/lib/recognizer/memory-conversation-context.js

As there are houndred of different database or storage engines, and there are millions of ways to develop how to identify a converstion, this is agnostic and up to you to implement your way to identify the conversation and to store in database. We had done this one in memory and with extraction of the conversation id from the session object of microsoft as an example.

You can see another example of how to implement the context store in a mongo database taking a look into the NLP.js-app (that does not use Microsoft Bot Framework at all). In this case the session identifier is a query parameter in the url:
https://github.com/axa-group/nlp.js-app/blob/master/server/feats/agent/agent.controllers.js#L463

In the implementation of the recognizer of the Microsoft Bot Framework you can see how we use this MemoryConversationContext:

```javascript
innerRecognize(session, cb) {
    const result = { score: 0.0, intent: undefined };
    if (session && session.message && session.message.text) {
      const utterance = session.message.text;
      const { locale } = session;
      this.conversationContext
        .getConversationContext(session)
        .then(async srcContext => {
          const context = srcContext;
          context.dialogId = this.getDialogId(session);
          const processResult = await this.process(context, locale, utterance);
          context.lastRecognized = processResult;
          this.conversationContext
            .setConversationContext(session, context)
            .then(() => cb(null, processResult))
            .catch(() => cb(null, processResult));
          return undefined;
        })
        .catch(async () => {
          const processResult = await this.process({}, locale, utterance);
          return cb(null, processResult);
        });
      return undefined;
    }
```

As you can see in this code the only thing that we asume from the Microsoft Bot Framework is that there exists a session object with a conversation identifier in some path... replacing this with another way to get this identifier makes this method works with your way.

I repeat: as there are hundred of storages/databases and millions ways to develop a session identifier, we cannot do this code for you, as you're the one that knows what kind of storage/database you're using or the way you have to identify sessions. Dialogflow has a session identifier generation, because it has connectors for channels so it has to identify for each channel conversation a matching session. NLP.js has not because is an NLU library, is up to each developer to decide where and how to connect it...

**Comment by Aliyss** [comment]
This is beautiful. Thanks a bunch.
