### ISSUE TITLE
Slot filling is not working as documented

### ISSUE THREAD

**Issue by obaid** [axa-group/nlp.js#242]
**Describe the bug**
Running the example found in the docs I found that the output is not as expected.

**To Reproduce**
See https://runkit.com/obaid/5d5abdd6eaec0b001442678f

**Expected behavior**
The console output should be:
Console output:
- Wow! You saw spiderman and iron man eating pasta!
- With whom did you see iron man?
- With whom did you see thor?
- What where they eating?
- Who did you see?

**Screenshots**
The output we get is:
- "Wow! You saw spiderman and iron man eating pasta!"
- undefined
- "With whom did you see thor?"
- "What where they eating?"
- undefined

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by jesus-seijas-sp** [comment]
Hello,

The problem is not the Slot Filling. This is happening beause since 3.4 we avoid false positives using a nonefeature that gives a weight into the intent None to sentences with unknown words.
To get the desired behaviour deactivate this option:
```javascript
  const manager = new NlpManager({ languages: ['en'], nlu: { useNoneFeature: false } });
```

**Explanation of the why**
NLP.js is for doing chatbots in production, we are working with it with thousands of utterances, houndreds of intents, and to avoid false positives is a must.

In a PoC, to play with it, you train something like:
"who are you"-> intent who
"good morning" -> intent greet
Then you say "who" and you expect to return the intent who....
But what if the user say "Tell me the last LP from The Who"... you expect to return the intent who? Nope, this will be a false positive.

So for test purposes you can deactivate it, but in production you should have it.

**Comment by obaid** [comment]
This works. Thanks for the details.
