### ISSUE TITLE
Reducing bundle size

### ISSUE THREAD

**Issue by ramezrafla** [axa-group/nlp.js#260]
**Is your feature request related to a problem? Please describe.**
The bundle size is 2.3MB -- making it unsuitable for website deployment

**Describe the solution you'd like**
We need to find a way to shake the tree (will webpack help) and remove uncommon packages

**Describe alternatives you've considered**
Haven't tested yet, will webpack help? Modularizing architecture to only keep most common features in core

**Additional context**
I am looking for guidance from @jesus-seijas-sp  who knows this package better, if there is room to trim things down. Maybe split off plugins or features not so common, like `xlsx` package, which would could reduce size substantially (does everyeone need `escodegen`,`kuromoji.js`, `novel-segment`?)

**Comment by jesus-seijas-sp** [comment]
Hello,
The web bundle was bigger than 20MB time ago... right now it does not includes xlsx, novel-segment or kuromoji.
It includes escodegen because is needed for conditional answers based on context conditions.

The problem is that it includes the languages information, example, all the trigrams for recognize the language, all the stopwords for indonesian, all the rules for stemming each language....

The idea was to modularize using lerna, so you can decide the languages to include, or if you want the language recognizer. Unfortunatelly, we don't have enough contributors to achieve a so huge architecture change.

On the other hand, the web bundle only has sense if you cannot pay to deploy as an API or you want to work without connection. If is the first case, I recommend you heroku. If is the second case, you can use the react-native version of the library and build the android and ios app. The common use of this library is in the backend not in the frontend, so usually the changes on the code focus in the backend part, not in minimizing the bundle for web.

**Comment by ramezrafla** [comment]
Thanks @jesus-seijas-sp 

I'll go through the library and see if I can contribute

We are trying to make of the computation client-side to improve the user experience (we are using GatsbyJS for our static website), as well, to have better control over the conversation. If we use Amazon Lex for example, it gets complicated quickly with Lambda functions to change intent on the fly etc. But with a good conversation plan we can do so much client-side 

Right now, we are developing with [compromise](https://github.com/spencermountain/compromise) (~200kb) but it has its limits

**Comment by jesus-seijas-sp** [comment]
If you're using compromise then your target is only english.... if that's the case, I have a tiny version of the NLU supporting english, and even emojis, with 0 dependencies, and the code is very small (less than 53K without even minimizing the code). https://github.com/jesus-seijas-sp/small-nlu.git
