### ISSUE TITLE
Intents with small utterance length are not triggered if there is a small error in user input

### ISSUE THREAD

**Issue by qwertyuu** [axa-group/nlp.js#263]
**Describe the bug**
Hello! Thanks for the great library. Very nice to use!
I am having a problem where I have a simple "greetings" intent with source utterances such as:
`Bonjour!`
`Bonjour`
`Salut`
`Hello`
`Hey`

If the user inputs: `Bonjou` or `Bonjourd` (a one letter difference from the source utterances), `None` is the output I get from the classifier. In other words, one-worded intents do not get error corrected.

I am posting here to get your input as to how I should go about solving that issue, or if it has been discussed somewhere else.

**To Reproduce**
1. Make an intent with a single word as a source utterance, train it
2. Input that word but make a simple mistake (add, modify or remove a letter)
3. You get a `None` intent output

**Expected behavior**
I would expect to get the "greetings" intent but with a lower accuracy score than one. 

**Screenshots**
When debugging, I found that on line 378 of `base-nlu.js` none of the feature EXACTLY match my input, hence why I get no results.
![image](https://user-images.githubusercontent.com/3145639/65722063-73cd2680-e079-11e9-8c59-75f74c6251b3.png)

**Comment by jesus-seijas-sp** [comment]
Hello @qwertyuu, is not because the utterances are small, is because NLP.js does not implements an spell checker, so certain misspelled words are not correctly stemmed.

Now a spell-checker is implemented, in this PR: https://github.com/axa-group/nlp.js/pull/264

You have example of use at https://github.com/axa-group/nlp.js/blob/master/test/nlp/nlp-manager.test.js#L1740

As you can see the use is optional, activated by { nlu: { spellCheck: true }}. By default is false.

**Comment by jesus-seijas-sp** [comment]
Closing as  is solved
