### ISSUE TITLE
Build a CHANGELOG.md file

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#265]
Build a changelog file with information of the last versions (from the commit info).

**Comment by svenewers** [comment]
I'd like to start work on this if that's all right?

**Comment by jesus-seijas-sp** [comment]
Of course! you're welcome!

**Comment by Big-Zude** [comment]
I would like to work on this too

**Comment by svenewers** [comment]
Hey there, just a quick update on progress on this issue:  
I had initially tried to maybe auto-generate the changelog using the git log & GitHub issues data and a small script, but that quickly turned out to be impressively impractical. So I'm now typing up a the changelog by hand starting from version 2.0.0 in a way that adheres to the "keepachangelog.com" standard. It's a bit of a laborious task to manually go through all the commits but I should be done by tomorrow and have a pull-request ready by then. (First progress can be seen [in my fork used for working on this issue](https://github.com/svenewers/nlp.js/blob/master/CHANGELOG.md))

**Comment by jesus-seijas-sp** [comment]
Thank you!!
