### ISSUE TITLE
Cannot find module 'node-nlp' after installing

### ISSUE THREAD

**Issue by ndtreviv** [axa-group/nlp.js#288]
**Describe the bug**
I installed node-nlp according to the documentation, but when I try to use it in the node repl I get:
```
> const { NlpManager } = require('node-nlp');
Thrown:
{ Error: Cannot find module 'node-nlp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18) code: 'MODULE_NOT_FOUND' }
```

**To Reproduce**
1. `> npm install --global node-nlp`
2. `> node`
3. `> const { NlpManager } = require('node-nlp');`

**Expected behavior**
It should be installed and accessible as a module, according to the documentation.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Mojave 10.14.6

**Comment by jesus-seijas-sp** [comment]
Hello,

I don't think it should work like that... 

You're trying to use the library from the node REPL, not from a node project. And it seems that your global node_modules is not in your path... If you really really want to use libraries from the Node REPL, try to see which paths are involved, you only have to:

```bash
export NODE_DEBUG=module
> require('node-nlp')
```

But this is not how the people woks with node.js. You usually start a project and install the dependencies locally to the project:

```bash
mkdir myproject
cd myproject
npm init
...
npm install node-nlp
```

The reason is that if you install globally, you'll only have a fixed version of each library... but different projects can have different versions of the libraries over time, so package.json of the project helps to maintain this.

**Comment by jesus-seijas-sp** [comment]
hello @ndtreviv , did you had time to check?

**Comment by ndtreviv** [comment]
Yes, your surmise was correct! Thanks.

**Comment by sjain3097** [comment]
can we use this in react js

**Comment by jesus-seijas-sp** [comment]
@sjain3097 yes, follow this guideline: https://github.com/axa-group/nlp.js/blob/master/docs/v4/webandreact.md
