### ISSUE TITLE
Difference between Brain NLU and Bayer NLU

### ISSUE THREAD

**Issue by danbulant** [axa-group/nlp.js#316]
What's the difference between Brain NLU and Bayer NLU? The code is nearly the same, only Brain changed to Bayer and you have better results (same thing with brain = 90 where bayer = 98)

**Comment by jesus-seijas-sp** [comment]
I think you mean Bayes...
BrainNLU is the best classificator for Conversational AI, using neural networks, and is the default, tested with different corpus, in fact in the folder examples you have a benchmark with 5 different corpus.
Bayes is simply a bayessian classifier... it does not uses neural networks. In the benchmark if you use the Bayes classifier you'll get worst results. Those are the results with the Brain:

![image](https://user-images.githubusercontent.com/15154218/67959563-41bf5f00-fbf9-11e9-8e75-58bfed6319ed.png)
The accuracy is 96.31%, and if you take a look into the three first corpus results, that are from the SIGDIAL22, you'll notice that the accuracy is greater than 0.93... the record was on IBM Watson with 0.92...

With Bayes:
![image](https://user-images.githubusercontent.com/15154218/67959723-76331b00-fbf9-11e9-835a-1b88b9cc6ff6.png)
The accuracy drops to 34.48%. Because is not a neural network, is only a probability. Works very well with very small problems, but not with real life chatbots.

My recommendation is: don't play with the subclasses, play with the NlpManager as is, because is configured to give you the best results for a production chatbot with the best understanding of the language. 

Also, I'm working on version 4. In version 4 Bayes will be removed, only Brain will exists (now renamed to Neural). You can be a preview at branch "next"

**Comment by danbulant** [comment]
Oh OK. I just didn't know, because in the docs, the text content is nearly the same, but with Bayes you got higher chance. I did just use the default config for my chatbot.
