### ISSUE TITLE
result of BayesNLU classifier seems erroneous.

### ISSUE THREAD

**Issue by edelah** [axa-group/nlp.js#318]
**Describe the bug**
the probability for intent 'greet' should be higher in the displayed result:
[ { label: 'greet', value: 0.5 },
  { label: 'keys', value: 0.5 } ]

**To Reproduce**
const { BayesNLU } = require('node-nlp');

async function main() {
    const classifier = new BayesNLU({ language: 'fr' });
    classifier.add('Bonjour', 'greet');
    classifier.add('bonne nuit', 'greet');
    classifier.add('Bonsoir', 'greet');
    classifier.add("J'ai perdu mes clés", 'keys');
    classifier.add('Je ne trouve pas mes clés', 'keys');
    classifier.add('Je ne me souviens pas où sont mes clés', 'keys');
    await classifier.train();
    const classifications = classifier.getClassifications('Bonsoir');
    console.log(classifications);

}
main();

**Expected behavior**
probability of intent 'greet' should be 1.

**Desktop (please complete the following information):**
 - node-nlp@3.10.2
 - version nodejs: v10.15.0

**Comment by jesus-seijas-sp** [comment]
Is because the Laplace smoothing, it is intended to have the smothing if the feature provided does not belong to the set of features, in this case is returning the smoothing by error because the value is 0...

You can try setting the smoothing to a very low value.

```javascript
async function main() {
  const classifier = new BayesNLU({ language: 'fr' });
  classifier.classifier.setSmoothing(0.000001);
  classifier.add('Bonjour', 'greet');
  classifier.add('bonne nuit', 'greet');
  classifier.add('Bonsoir', 'greet');
  classifier.add("J'ai perdu mes clés", 'keys');
  classifier.add('Je ne trouve pas mes clés', 'keys');
  classifier.add('Je ne me souviens pas où sont mes clés', 'keys');
  await classifier.train();
  const classifications = classifier.getClassifications('Bonsoir');
  console.log(classifications);
}
main();
```

On the other hand, the next version of nlp.js will not include BayesNLU neither BayesClassifier to avoid that the people use it. It's very proved that the results of Bayes in conversational AI has a very low accuracy for real chatbots, so it was not maintained, and will be totally removed in next versions.

**Comment by jesus-seijas-sp** [comment]
Closing. It was solved and also we no longer support Bayesian NLU
