### ISSUE TITLE
The dependency `kuromoji`, that seems to be used for JP processing is too big

### ISSUE THREAD

**Issue by FMS-Cat** [axa-group/nlp.js#362]
I'm not using Japanese recognition at all but the library still comes with 44MB of unnecessary Japanese recognition library.
If we can make languages selectable that would be good.

I'm Japanese though :)

**Comment by jesus-seijas-sp** [comment]
Hello!
In fact the version 4 is modular, so you install only what you need, every language is a different package, but we have the module "node-nlp" to be retrocompatible as much as we can with version 3.

In this case, is your project for backend, web or mobile? To ilustrate how to do it, I created some examples you can get here: https://github.com/jesus-seijas-sp/nlpjs-examples

The example 01 is backend with a console connector to test, and only english. You only have to install the package @nlpjs/basic, then create a configuration file conf.json. To explain the conf.json:
```json
{
  "pathPlugins": "./plugins",
  "pathPipeline": "./pipelines.md",
  "settings": {
    "nlp": {
      "autoLoad": true,
      "autoSave": true,
      "corpora": [
        "../corpora/corpus-en.json"
      ]
    }
  },
  "use": ["Basic", "ConsoleConnector"]
}
```
The most important part is the "use", where I'm telling the application what plugins to mount. The "Basic" name install the basic plugins to work: a logger, a filesystem, the nlp, the ner and the english language. The ConsoleConnector is telling it to use also a ConsoleConnector for the chatbot. The pluginsPath is telling where to load custom plugins... but there is none in this case. The settings is defining the settings for the nlp, basically that if it trains a model, saves it automatically, and if a model exists does not train and load it instead, and also where to find the corpus. The pipelines is where to find the pipelines, that is an md file that looks like this:

```markdown
# default

## main
nlp.train
console.say "Say something!"

## console.hear
// compiler=javascript
if (message === 'quit') {
  return console.exit();
}
nlp.process();
this.say();
```
The title of the markdown represents the name of app (or container...), basically you can have multiple apps/containers where they can use resources from the parent container, so the memory consumption is lower. The main is telling it what to do during the initialization. The "console.hear" is what to do when the console reads a line (every connector has a hear and say method). Also the compiler specified is javascript, so I'm using javascript there (python can be also used installing the @nlpjs/python-compiler package).

The example02 is similar but also installing the spanish language and using 2 corpus: one english and one spanish.

The example 03 is different, is how to build it for web. There is no conf.json, is in the code, and as web does not have a filesystem, is installing a web filesystem that allows it to read the corpora from an url. Also it shows how to create a container and load plugins into it without the conf.json, and how to get objects from the container (in this case, the nlp object). In this example you can run "npm run browserdist" and it will generate a web version called bundle.js with all the code in the folder dist, you'll notice that the size is only 324KB, that is 10 times lower than in version 3 (it was more than 3MB).

Also, if you want to use all the languages, there is a LangAll package so when you install it as a plugin it install all the languages.

Ah, in the web version, if you don't use the english sentiment, you can install @nlpjs/lang-en-min instead of @nlpjs/lang-en, it will reduce the bundle size from 324KB down to 156KB (yes, the sentiment analysis dictionaries are huge)

**Comment by FMS-Cat** [comment]
Thanks for the well described answer, was it available somewhere in README? I might have not noticed to that...
Yes, I actually knew it is almost shaped like a modular since hitting `yarn why kuromoji` told me it comes from `node-nlp#@nlpjs#lang-all#@nlpjs#lang-ja` .
But I have had zero ideas how do I use them on my own.
Let me try this!

**Comment by jesus-seijas-sp** [comment]
Hello, I started the documentation of the version 4, you can read it here:
https://github.com/axa-group/nlp.js/blob/master/docs/v4/quickstart.md
For web and react native: https://github.com/axa-group/nlp.js/blob/master/docs/v4/webandreact.md

**Comment by jesus-seijas-sp** [comment]
Closing, as in version 4 is modular
