### ISSUE TITLE
Every language is loaded even though I only specify one

### ISSUE THREAD

**Issue by qwertyuu** [axa-group/nlp.js#403]
Hello Jesus! Again, thanks a whole lot for the library. Our team loves it, and we are glad that you are so responsive when opening issues. Very nice job, I am sure that you bring joy to a whole lot of people and your family 🥇 

**Describe the bug**
After upgrading to v4.1.0, I saw a console log "Compiling dictionary" appear when I booted up my app. I thought this was normal but I also saw a slowdown, so I searched for the log in the code.

Turns out there is only one place where it is present, and it is in the "lang-zh/src/dictionary.js" file at "start()" function. Thing is, I am french and I only use the french dictionary, but after putting a breakpoint there, I saw that all dictionnaries are initialized and compiled, even though they are not used. This causes a real slowdown on initialization.

I think this is caused by: src/nlp/nlp-util.js, line 30 where `const LangAll = require('@nlpjs/lang-all');`. This indeed loads ALL dictionnaries of all languages no matter the languages I need. This means, at import time, even before calling the NlpManager constructor, all dictionnaries are processed.

**Expected behavior**
The languages I specify when booting the NlpManager (`languages` option array) should be started/compiled

**Comment by jesus-seijas-sp** [comment]
Hello!

You're totally right. Dictionaries and stuff that can affect to the performance at cold start, should follow a lazy load strategy, and only load the first time that are called. 

I take the point.

**Comment by jesus-seijas-sp** [comment]
Hello!
Is fixed in the version 4.2.1 of node-nlp.

If you want to increase performance and reduce size, I suggest to not use node-nlp dependency, but to work with the plugin system, so you only install what you need (if you only use 2 languages... you only install those 2 languages).
I suggest you do the quickstart guide: https://github.com/axa-group/nlp.js/blob/master/docs/v4/quickstart.md

If you want to have more simple corpus, only Q&A instead of the concepts of intent, utterance... then now Q&A TSV files can be used and are converted automatically into valid corpus:
https://github.com/axa-group/nlp.js/blob/master/docs/v4/qna.md

If you target mobile applications or web that should work offline without a backend, you can do the web/react native guide: https://github.com/axa-group/nlp.js/blob/master/docs/v4/webandreact.md
