### ISSUE TITLE
Question: How to get entities in V4

### ISSUE THREAD

**Issue by ohager** [axa-group/nlp.js#407]
Hi there.

I'm struggling with the NER. As the documentation for V4 is pretty sparse yet, I'm not able to figure out how to make get entities to be recognized. I tried to follow the V3 docs and even searched the issues  but no luck yet.

Here an example of a processed result.
 
```
{
  message: 'See you next Monday',
  channel: 'console',
  app: 'default',
  locale: 'en',
  utterance: 'See you next Monday',
  languageGuessed: false,
  localeIso2: 'en',
  language: 'English',
  nluAnswer: {
    classifications: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    entities: undefined
  },
  classifications: [
    { intent: 'intent.date', score: 0.6568577927856984 },
    { intent: 'intent.greeting', score: 0.18801544966162007 },
    { intent: 'None', score: 0.07579000721592986 },
    { intent: 'intent.birthday', score: 0.0739171481465045 },
    { intent: 'intent.joke', score: 0.005419602190246988 },
    { intent: 'intent.quit', score: 0 }
  ],
  intent: 'intent.date',
  score: 0.6568577927856984,
  domain: 'default',
  sourceEntities: [],
  entities: [],
  answers: [],
  answer: undefined,
  actions: [],
  sentiment: {
    score: 0,
    numWords: 0,
    numHits: 0,
    average: 0,
    type: undefined,
    locale: 'en',
    vote: 'neutral'
  }
}
```
I expect to have at least one recognized entity `Monday`

Maybe I just need to configure correctly... currently, I have this:

```{
  "settings": {
    "nlp": {
      "autoSave": true,
      "corpora": [
        "./src/corpora/en.json"
      ]
    },
    "ner": {
      "threshold": 0.8
    }
  },
  "use": ["Basic", "ConsoleConnector"]
}
```

**Comment by jesus-seijas-sp** [comment]
Hello,

You're right, there is no docs about it... In the version 3.x by default there is a builtin extractor using Microsoft library, and you can change it to set duckling. The problem was that you were boxed to use one or the other... what if you want to use a different one developed by you? Or if you want to use one for a language a the other for another language?

Also other problem was the size... when compiling the product for react it was oversized by the regular expressions, so now is an optional library.

Third problem: having Microsoft Recognizers by default makes a lot of problems with french extraction, due to regular expresions that get freeze.

So... How to have builtin entity extraction.

Step 1: install the plugin that you need. If you have a duckling up and running the plugin is @nlpjs/builtin-ducklin. Let's supose that is not the case and you want to use the Microsoft recognizers. 

```sh
npm i @nlpjs/builtin-microsoft
```

Second step is to add it as a plugin. Adding "BuiltinMicrosoft" to the use section will not help, it will add the plugin but not connected to the ner... because the ner expects those extractors to have the name "extract-builtin-{locale}" (example, "extract-builtin-en"). But in the use section you can use a plugin (even several times) and register it with different names... In our case to simplify lets think that you want to add the BuiltinMicrosoft to be the extractor for all languages, then you can register it as "extract-builtin-??" or "extract-builtin-*". If you after that register a plugin "extract-builtin-en" for english will use this last plugin, for other languages will use the one with the wildchars.

So modify your configuration:
```javascript
  "settings": {
    "nlp": {
      "autoSave": true,
      "corpora": [
        "./src/corpora/en.json"
      ]
    },
    "ner": {
      "threshold": 0.8
    }
  },
  "use": ["Basic", "ConsoleConnector",
    { "className": "BuiltinMicrosoft", "name": "extract-builtin-??", "path": "@nlpjs/builtin-microsoft"}
]
}
```

And that's all, you will your "monday" resolved as an entity.

**Comment by ohager** [comment]
Worked! Thanks for explanation.

**Comment by Aliyss** [comment]
Probably a similar question. But more interested in the sentiment part. Seems the whole sentiment stuff is 0

**Comment by TahianaRakotolobo** [comment]
Hi. Is it possible to create a new type of entity? If it is, then could you tell me how to do that? Thank you.
