### ISSUE TITLE
BrainNLU is not a constructor

### ISSUE THREAD

**Issue by abtx** [axa-group/nlp.js#441]
**Describe the bug**
I've imported  BrainNLU from node-nlp and I'm getting `BrainNLU is not a constructor` error. Importing NlpManager works, on the other hand.

**To Reproduce**
1. add `import { BrainNLU } from 'node-nlp'`
2. add `const classifier = new BrainNLU({ language: 'en' });`
3. See error

**Expected behavior**
Initialise the classifier with provided method

**Desktop (please complete the following information):**
 - OS: OsX 10.15.4
 - Safari
 - Package version 4.3.0
 - Node version 13.12.0

**Comment by ooorndtski** [comment]
Hi abtx,

I think the problem is, that BrainNLU as well as BayesNLU and the other ones, are not existing any more. At least I havn't found any references in the code.

The documentation seems not to be up to date, I think, because the [here](https://github.com/axa-group/nlp.js/blob/master/docs/v3/brain-nlu.md) the path "docs/v3/...".

I checked this using version 4.4.0.

**Comment by adelriosantiago** [comment]
Where did they go? I was looking for `BrainNLU` as well 😮

**Comment by jesus-seijas-sp** [comment]
@adelriosantiago BrainNLU was the NLU based on Brain.js that existed months ago. The new NLU is faster  (about 7 times faster, we passed from 6.300TPS up to 47.000TPS), with better precision and recall (about 2 or 3% better in different corpus), because is built specifically for NLU models and is not a generic one. What is the rational behind wanting the old slower and not so accurate NLU?

**Comment by adelriosantiago** [comment]
@jesus-seijas-sp Ahh I see, makes sense now. The reason I was looking for `BrainNLU` is because I wanted to match text to intent only. No, sentiment analysis, or answers. Somethin like a _quick text to intent match_.

**Comment by abtx** [comment]
@adelriosantiago I was looking for the similar type of usage. Did you find any other libs useful?
