### ISSUE TITLE
How to have entities affect intent recognition?

### ISSUE THREAD

**Issue by kootenpv** [axa-group/nlp.js#537]
It looks that whenever an entitiy is added/removed, it has no influence on the result of intent recognition.

Is there some kind of way that allows us not to have to provide all entity variation as examples for intents, but instead have some generalization?

**Comment by luddilo** [comment]
I'm also curious about this. In Dialogflow and (as far as I am aware) also in Rasa, entities will affect intent classification and there are concepts like mandatory entities (as opposed to optional ones). @jesus-seijas-sp how is this done in this framework?

**Comment by jesus-seijas-sp** [comment]
Let's see this example:
```javascript
const { NlpManager } = require('node-nlp');

function train(manager) {
  manager.addNamedEntityText('city', 'BCN', 'en', ['Barna', 'Barcelona']);
  manager.addNamedEntityText('city', 'MAD', 'en', 'Madrid');
  manager.addNamedEntityText('city', 'AGP', 'en', 'Malaga');
  manager.addDocument('en', 'I want to travel to Barcelona', 'travel');
  manager.train();
}

async function main() {
  const manager = new NlpManager({ languages: ['en'] });
  await train(manager);
  const result = await manager.process('en', 'I want to travel to barna');
  console.log(result);
}

main()
```
This gives us an score of 0.94, because "barna" !== "barcelona" so are different features.

Now let's change the utterance added:
```javascript
manager.addDocument('en', 'I want to travel to %city%', 'travel');
  ```
This gives us an score of 1, because from the utterance "'I want to travel to barna'" another one is generated because the NER identifies "barna" as an enity and generates the optional utterance "I want to travel to %city%" that matchs exactly the one of the training. To understand it better, when an utterance A is classified, an utterance B is generated replacing entities, both are classified, and the best classification is chosen.

Important note here: in version 3 the format for entities was "%entity%", in version 4 the format is "@entity", so if you use "node-nlp" the format is the version 3 one, but if you use NLP.js in a different way then by default is the @. You can also change the entity preffixes and suffixes using configuration.

**Comment by kootenpv** [comment]
Thanks @jesus-seijas-sp!
