### ISSUE TITLE
Language guesser fails (80% times)

### ISSUE THREAD

**Issue by GuillermoPena** [axa-group/nlp.js#761]
**Describe the bug**
5 tests. 4 errors. Am I doing something wrong?

 
```javascript
  const { Language } = require('@nlpjs/language')
  const lang = new Language()
  const allowList = ['en', 'es', 'fr']

  let text = "soy un fontanero bajito con bigote y un mono rojo"
  let output = lang.guessBest(text)
  console.log('\nGuessing language of: "' + text + '"')
  console.log(output)
  // ERROR : { alpha3: 'ita', alpha2: 'it', language: 'Italian', score: 0.8960660514813016 }

  output = lang.guessBest(text, allowList)
  console.log('\nGuessing language of: "' + text + '" - Allowed languages: ' + allowList)
  console.log(output)
  // ERROR : { alpha3: 'fra', alpha2: 'fr', language: 'French', score: 1 }

  text = "i like cats"
  output = lang.guessBest(text)
  console.log('\nGuessing language of: "' + text + '"')
  console.log(output)
  // ERROR : { alpha3: 'cat', alpha2: 'ca', language: 'Catalan', score: 1 }

  output = lang.guessBest(text, allowList)
  console.log('\nGuessing language of: "' + text + '" - Allowed languages: ' + allowList )
  console.log(output)
  // ERROR : { alpha3: 'fra', alpha2: 'fr', language: 'French', score: 1 }

  text = "me gustan los gatos"
  output = lang.guessBest(text, allowList)
  console.log('\nGuessing language of: "' + text + '" - Allowed languages: ' + allowList)
  console.log(output)
  // Ok : { alpha3: 'spa', alpha2: 'es', language: 'Spanish', score: 1 }
```

**Desktop (please complete the following information):**
 - Package versions:
    "@nlpjs/basic": "^4.17.5",
    "@nlpjs/lang-all": "^4.17.1",
    "@nlpjs/lang-es": "^4.17.0",
    "@nlpjs/language": "^4.17.0"
 - Node version: v14.15.0

**Comment by jesus-seijas-sp** [comment]
Hello,
**First, bad news**: yes, that's true, the guessing of the language is done with most common trigrams of a language, so for short texts this is not accurate.

**Second, worst news**: if you use another guessing tools, it will also fail. You can try with franc, that is the most popular:

```javascript
const franc = require('franc')
const { Language } = require('@nlpjs/language')

const lang = new Language();
const allowList = ['en', 'es', 'fr'];

function guess(sentence) {
  console.log(franc(sentence));
  console.log(lang.guessBest(sentence));
  console.log(franc(sentence, { only: ['spa', 'fra', 'eng']}));
  console.log(lang.guessBest(sentence, allowList));
}

guess('soy un fontanero bajito con bigote y un mono rojo');
```

This returns:
```
vec
{
  alpha3: 'ita',
  alpha2: 'it',
  language: 'Italian',
  score: 0.8960660514813016
}
fra
{ alpha3: 'fra', alpha2: 'fr', language: 'French', score: 1 }
```

So exactly same result, but franc returns "venetian" instead of "italian" for the sentence.

**Third, very good news!!!!**
NLP.js use the language library, but it's intended to be used with chatbots, so... of course you have a corpus to train the chatbot, no? The language library learn the trigrams from the corpus that you use, so if you have 3 corpus, one in spanish, one in french and one in english, the language library automatically learn the trigrams from the utterances of each corpus, so is very accurate to guess the sentences of your users.

**More good news** 
Well, perhaps you don't want to use it inside a chatbot, but you now the domain of the information that you want to use and you have texts... then you can train the Language class from your documents.

**Comment by GuillermoPena** [comment]
Yes. In chatbot it works ok. 
Thanks Jesus!
