### ISSUE TITLE
Is keepStopword working?

### ISSUE THREAD

**Issue by GuillermoPena** [axa-group/nlp.js#767]
**Describe the bug**
I have a trained a nlp and i try process a utterance expecting to obtain 'None' intent but i obtain 'bye' intent.
Test utterance is "la vida pasa", in spanish. The only word used in test and training utterances is "la" (in training utterance "hasta la proxima").

I check that "la" is a stop word and I'm trying to set keepStopword = false but I'm doing something wrong becase it doesn't seem to be some effect. 

If I remove "la" from utterance nlp return 'None' intent. If keep "la", it returns 'bye' intent

Test code: 
```javascript
const { dockStart } = require('@nlpjs/basic');
const LangEs = require('@nlpjs/lang-es');

const go = async () => {
  const dock = await dockStart({ use: ['Basic']});
  const nlp = dock.get('nlp');
  nlp.container.use(LangEs.LangEs);
  nlp.addLanguage('es');

  nlp.settings.autoSave = false;
  nlp.nluManager.settings.log = false;

  // Adds the utterances and intents for the NLP
  nlp.addDocument('es', 'hasta luego', 'bye');
  nlp.addDocument('es', 'cuidate', 'bye');
  nlp.addDocument('es', 'nos vemos', 'bye');
  nlp.addDocument('es', 'hasta la proxima', 'bye');
  nlp.addDocument('es', 'me tengo que ir', 'bye');
  nlp.addDocument('es', 'hola', 'hello');
  nlp.addDocument('es', 'buenos dias', 'hello');
  nlp.addDocument('es', 'que tal?', 'hello');

  const configNluEs = nlp.container.getConfiguration('nlu-es');
  configNluEs.keepStopwords = false;
  console.log('\nNLU-Es Settings: ');
  console.log(configNluEs);

  const stopwords = nlp.container.get('stopwords-es');
  console.log('\nIs "la" a stop word? ' + stopwords.isStopword('la')); //true

  await nlp.train();

  let response = await nlp.process('es', 'la vida pasa');
  console.log('\nTest Utterance: "la vida pasa"');
  console.log(response);  // intent "bye"

  response = await nlp.process('es', 'vida pasa');
  console.log('\nTest Utterance: "vida pasa"');
  console.log(response);  // intent "None"
}

go();
```

**Versions:**

"@nlpjs/basic": "^4.17.5",
"@nlpjs/lang-all": "^4.17.1",
"@nlpjs/lang-es": "^4.17.0",
"@nlpjs/language": "^4.17.0"
Node version: v14.15.0

**Comment by GuillermoPena** [comment]
...and Merry Xmas!!

**Comment by jesus-seijas-sp** [comment]
Hello @GuillermoPena ,

The **dockStart** is the responsible of reading the configurations and creating the instances, so when you're modifying the configuration of **nlu-es**, it will affect to new instances of the **nlu**, but the instance is already created so it's settings are already created with the by default **keepStopwords = true**.

Two ways that you can change it:

1. At **dockStart** provide the settings:
```javascript
  const dock = await dockStart({ use: ['Basic'], settings: { 'nlu-es': { keepStopwords: false }}});
```

2. Modify the settings in the **nlu** instance for the domain **master_domain** of the language **es**. This will work because you only have one domain, so the name of the domain will be **master_domain**
```javascript
  nlp.nluManager.domainManagers.es.domains.master_domain.settings.keepStopwords = false;
```

I recommend using the solution 1, also if you're not in a browser, use a **conf.json** to extract the configuration from the development, as is reflected in the quickstart.

**Comment by GuillermoPena** [comment]
Working!
Thanks again Jesus.
