### ISSUE TITLE
How to process dialog variables

### ISSUE THREAD

**Issue by marcpascualsanchez** [axa-group/nlp.js#832]
Apparently, when I use dialog variables in conditions like this:
```
dialog ask_sunny
  say Is it sunny?
  ask isSunny
  [isSunny === 'yes'] say it is sunny!
  [isSunny === 'no'] say it is not sunny...
```
The value of `isSunny` must be "yes" or "no" in order to answer. Therefore it does not work if it is mispelled like "yez".
Is there any way to process the variables used in a dialog file, like an intent?

Thank you

**Comment by jesus-seijas-sp** [comment]
You have the validators.

One example:
```
const validatorYesNo = (session, context, params) => {
  if (session.text && session.text.toLowerCase().includes('no')) {
    return {
      isValid: true,
      changes: [{ name: params[0], value: 'no' }]
    }
  }
  if (session.text && session.text.toLowerCase().includes('yes')) {
    return {
      isValid: true,
      changes: [{ name: params[0], value: 'yes' }]
    }
  }
  return {
    isValid: false,
  }
}

module.exports = { validatorYesNo };
```

Validators can be async, so you'll have no problem to play with whatever from there.
Understand a validator as something that receives plain text, process it, and return tuples name/value so this info will be replaced in the context. Why tuples? Because from one text you can modify n context variables.
Also a validator returns isValid to tell if this plain text contains something valid.

In a bot you register a validator like this:
```javascript
bot.registerValidator('yesNo', validatorYesNo);
```

Once done that you have to options to use validators.
First: in an ask, put the name of the validator at the end:
```
dialog ask_sunny
  say Is it sunny?
  ask isSunny yesNo
  [isSunny === 'yes'] say it is sunny!
  [isSunny === 'no'] say it is not sunny...
```

Second: it automatically creates a new "ask" with the name of the validator capitalized:
```
dialog ask_sunny
  say Is it sunny?
  askYesNo isSunny
  [isSunny === 'yes'] say it is sunny!
  [isSunny === 'no'] say it is not sunny...
```

**Comment by marcpascualsanchez** [comment]
This potentially solves the problem. I mean, in this case, if "yez" was the answer, it would return `{ isValid: false }`.
I assume inside the validator I could have nlp object so it could process the text (like the `NlpManager` class) and have a more reliable answer. Would that be the best approach?

Thanks a lot!

**Comment by jesus-seijas-sp** [comment]
Yes, you can, like that:

```javascript
const { dock } = require('@nlpjs/basic');

const validatorYesNo = async (session, context, params) => {
  const nlp = dock.get('nlp');
  const lang = context.locale || 'en';
  const response = await nlp.process(lang, session.text)
  <you logic here>
```

**Comment by marcpascualsanchez** [comment]
Nice, this will solve it nicely, thank you very much for the fast response and clear instructions. Your help is really appreciated.
