### ISSUE TITLE
Cannot read property "length" of undefined when using BIG corpus!

### ISSUE THREAD

**Issue by ignStonechat** [axa-group/nlp.js#866]
## Cannot read property "length" of undefined when using BIG corpus!

So, Hello!
Today I finally completed extracting all the stuff I need from 10GB worth of medical dataset.
now, of course I cut it up a bit and organized it and made it about 2.5GB a file, and so I got the error.
I knew it wasnt my code but I checked my code with the test data thats just abt 500kb.
so I then tried just 5MB. guess what. same. error. o ma gad.
how do I work around this. I dont want to make my files 500kb EACG?! that would be LIKE A MILLION FILES!
So I need help how do I work around this.

here is the error
![image](https://user-images.githubusercontent.com/64982639/108697957-f41ce300-751c-11eb-9de9-9940f2c85119.png)

**Comment by jesus-seijas-sp** [comment]
This is the part of code generating this error:
![image](https://user-images.githubusercontent.com/15154218/108698614-9da3aa80-7504-11eb-8364-edde3f2d75b3.png)

So this happen if utterances does not exist, so perhaps you have intents inside your corpus that does not contain the utterances property.

On the other hand, this NLP is for building chatbots, a corpus with 10.000 intents and an utterance per intent and an answer is about 1.4MB,... And we are talking of 10.000 intents, take into account that Dialogflow and IBM Watson supports 2.000 intents, Microsoft LUIS supports 500 intents, and the last time I tried with RASA it was not able of processing 300 intents (I don't know now).
So when I read the 2.5GB of corpus there, I don't think that this will fit on a classifier for chatbots.

**Comment by ignStonechat** [comment]
Oh understandable, actually I didn't know there was a limitation...
Is there anything u could recommend? I am trying to build an AI "chatbot" basically just trying to make super smart AI that can help people. but medicine is big...
Also THANK YOU SO MUCH for such quick response

**Comment by ignStonechat** [comment]
Update: I tried using library called "natural" and it seems that it handles it all pretty well...
here is a random question I asked from my 10gb dataset.
![image](https://user-images.githubusercontent.com/64982639/108723013-3524ef80-753d-11eb-8ac9-d3d26fe7293b.png)

**Comment by jesus-seijas-sp** [comment]
Hi, what classifier did you used? With a Bayesian classifier it can be done, but results will not be good. With the Logistic Regression Classifier or Maximum Entropy I don't know how will be the behaviour.

**Comment by ignStonechat** [comment]
> 
> 
> Hi, what classifier did you used? With a Bayesian classifier it can be done, but results will not be good. With the Logistic Regression Classifier or Maximum Entropy I don't know how will be the behaviour.

I used Bayes. I didn't remember the other ones I will try them right now and update you

**Comment by ignStonechat** [comment]
Update: when using LogisticRegressionClassifier, tests died out from ram REALLY quickly.
And current situation about it with 4gb ram allocated is: its been going forever omg omg omg omg omg

**Comment by ignStonechat** [comment]
basically this here, that there. it takes forever I turned it off and its fine.

**Comment by jesus-seijas-sp** [comment]
Bayesian is a "naive" algorithm, it does not need a training, is a question of probaility.
When you go for Artificial Intelligence, it will mean this in memory, as a minimum (a LRC or a dense network):
(numInputs + 1) * (numOutputs) float numbers to be calculated. And to calculate these numbers, the optimizer will iterate all the sentences per epoch, for each sentence will calculate sums and multiplications with these numbers, calculate an error, modify the numbers... and move to next epoch if the error is not reasonable.
If you imagine a corpus with 1.000.000 intents with 5 sentences, that means 5.000.000 of sentences, so every single epoch the optimizer will execute those 5.000.000 of sentences agains the perceptrons of every single intent, that means 5.000.000.000.000 of iterations per epoch... and to train it will take more than one epoch. If you imagine 100 epochs, that makes 500.000.000.000.000 operations where the optimizer calculates the result for this sentence and modify the weights to mitigate the error. And what means modify the weights? Ok, for this corpus, 5.000.000 sentences, we can expect an average of 10.5 words per sentence, that means 52.500.000 words,  we can have like 400.000 unique words. This number is the number of inputs, so the amount of weights will be (400.000 (inputs) + 1 (bias of each perceptron)) * (1.000.000 (number of intents)) = 400.001 * 1.000.000 = 400,001,000,000 weights. If your optimizer has momentum, this is multiplied by 2, because you'll have to store also the changes for the momentum, that means a total of 800,002,000,000 floats in memory that will be recalculated for each sentence and each epochs... In a 64 bits system that means a minimum of 6,400,016,000,000 bytes, that is, 6 TB of memory while training, if then you drop the momentum changes you'll need 3TB in memory for running the model.

And well, for training, imagine the time: 800,002,000,000 float numbers modified during 100 epochs that is 500.000.000.000.000 operations of modifying those numbers....

**Comment by ignStonechat** [comment]
GOD! THATS A LOT OF MATH NO JOKE NO MEME!
I switched to wink which is working amazingly right now and their bayes classifier seems to be "better" then natural's.
Basically the differience is that lets say I used my history system that simulates open questions, and say first input was "who is michael jordan" and second input is "did he like dogs" its gonna find the name of someone and add it at the end of the sentence. then that answer is computed too and you get the result thats associated with michael jordan! in wink that works but in natural it doesn't.
