### ISSUE TITLE
Limiting which entities are parsed with NER based on intent

### ISSUE THREAD

**Issue by danbulant** [axa-group/nlp.js#966]
Is there a way to limit entities parsed by NER based on the selected intent?
When I have different entities (usually trim entities), it seems they all get checked regardless of the actual intent, even though most of the time they're irrelevant (and it just slows down nlp).
I always have the entities I want mentioned in the document (like `%entity%`), and when i add console log to NER `getEntitiesFromUtterance` I see they're being picked up correctly. Now I'd like NER to only parse related entities - or not parse them at all (I'm using NlpManager from `node-nlp`, not the new v4 syntax as I couldn't find enough docs for it), and let me somehow select which entities to try and parse.

**Comment by Apollon77** [comment]
I also stumbled over the fact that a trim entity is also returned if empty. So the question is ... should it be that way? 

In my eyes not because an empty string is not a match ...

**Comment by Apollon77** [comment]
I prepare a PR for it - also in connection to https://github.com/axa-group/nlp.js/issues/1174 ... but most likely PR nreeds to wait until my other 4 PRs are merged ... It starts to overlap code-wise, so else it gets a merge hell.

**Comment by ericzon** [comment]
Moving forward several topics. We added feedback to all the active PRs to be merged as soon as possible. We'll release a version after that.

**Comment by Apollon77** [comment]
Thank you, I saw that ... I will see that I find time the next days to get my brain into the topics again (it is several months ago as I made the PRs and paused all efforts after that to make sure to know how to comntinue - so I do not remember all the "why's" for the changes and such). And some things (e.g. srcAnswer) I need to reevaluate also because of the new infos you provided) Will try my best to provide adjustments

**Comment by ericzon** [comment]
thanks for effort @Apollon77 take your time

**Comment by Apollon77** [comment]
should be addressed by #1221
